FROM node:18

WORKDIR nest

CMD npm install && npm run start:dev
# CMD ["npm", "run", "build"]

#########
#npm install
#npm i -g @nestjs/cli
#nest new .
##sequlize
#npm install --save @nestjs/sequelize sequelize-typescript
#npm install --save-dev @types/sequelize
#npm install --save pg pg-hstore
#npm i @nestjs/config
##typeorm
#npm install --save @nestjs/typeorm typeorm pg
#npm i @nestjs/passport passport passport-42