FROM node:18

WORKDIR nest

#CMD ["npm", "install"]
#CMD ["npm", "run", "build"]

#########
#npm install
#npm i -g @nestjs/cli
#nest new .
#npm install --save @nestjs/seuelize sequelize-typescript
#npm install --save-dev @types/sequelize
#npm install --save pg pg-hstore
#npm i @nestjs/config


ENTRYPOINT ["npm", "run", "start:dev"]